"""add tasks table

Revision ID: 788fec0e673d
Revises: 
Create Date: 2023-04-20 19:40:30.488013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788fec0e673d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_image'), ['image'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_runtime'), ['runtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_runtime'))
        batch_op.drop_index(batch_op.f('ix_tasks_namespace'))
        batch_op.drop_index(batch_op.f('ix_tasks_name'))
        batch_op.drop_index(batch_op.f('ix_tasks_image'))

    op.drop_table('tasks')
    # ### end Alembic commands ###
